@extends('admin.layouts.master')


@section('title')
<title>Documentaion</title>

<style>
	.nav-area{
		float: left;
		width: 10%;
	}
	.front-end{
		float: left;
		width:44%;
		margin: 0% 1%;
	}
	.back-end{
		float: left;
		width:44%;
		
	}
</style>
@endsection





@section('content')

<!-- page title area  -->
<div class="row mb-2">
	<div class="col-12 text-right">
		<a data-toggle="tooltip" data-placement="top" title="Back" href="{{ url()->previous() }}" class="btn btn-primary"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i></a>
	</div>
</div>

<div class="documentaion">
	<div class="nav-area" >
		
		<nav class="nav flex-column">

		  <a class="nav-link  " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		  <a class="nav-link " href="#">Dashboard Doc</a>
		 
		</nav>
	</div>
	<div class="front-end" >

		<div id="dashboard" class="text-justify pt-5 ">
			<h3>This is documentaion of dashboard</h3>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque praesentium molestiae voluptatum tenetur quas rerum aperiam modi saepe dolor iure eaque minus corporis eum excepturi ab pariatur, quidem autem molestias porro doloribus quibusdam delectus officiis, voluptate? Quasi perferendis sint quis tempora consectetur eveniet aspernatur placeat hic molestiae, nihil. Voluptatem doloribus nobis quos ab vero, id necessitatibus repudiandae neque quam consectetur saepe minima harum, quisquam aliquid excepturi vel. Eius, nobis sapiente veritatis quos, ea non consectetur sed dolorem dolorum eum, mollitia. Illum explicabo sed reprehenderit, corrupti iusto sint quos praesentium est, perferendis aut quidem tenetur veritatis fuga reiciendis earum consequuntur obcaecati quas deserunt dolor, accusamus atque? Ut facere asperiores consequatur architecto, soluta officia consequuntur error numquam itaque commodi amet vitae, laboriosam modi ratione fugit accusantium consectetur quasi. Nisi quibusdam similique ipsa nam consectetur, expedita quis non. Tempora quasi nostrum velit, ex, animi fuga quos, assumenda fugit, amet maxime quaerat architecto sint quis quia doloremque ipsa unde! Quasi magnam vitae dolorum esse alias error, quidem blanditiis, vel debitis nulla sint minima temporibus mollitia id qui maiores asperiores placeat iusto sed. Consequatur minus molestias ducimus, repellendus neque. Dolore, eveniet eius omnis, alias architecto minus! Perspiciatis dicta minima ducimus minus praesentium quisquam, nobis est esse quasi sint quo laudantium ipsum rerum labore, maiores odio, repellendus nostrum assumenda illum quaerat distinctio eius animi pariatur! Perspiciatis, fugiat modi asperiores odio enim fugit voluptates, dolores esse dolorem, at similique? Beatae fugiat totam voluptatem incidunt, maxime, a laboriosam ipsam aperiam nobis repellendus iste, expedita aut, quisquam eligendi. Repellendus voluptas possimus non corrupti officiis deleniti nostrum enim molestias rem odio, quia fuga id blanditiis optio earum odit maiores, reprehenderit nisi et. Enim, fugit odio aliquid sed laboriosam dignissimos, veniam accusamus unde sequi minima dolorem ducimus libero. Magni explicabo eveniet deserunt libero, facere neque mollitia quod tenetur nam doloribus reiciendis.</p>
		</div>

		<div id="dashboard" class="text-justify pt-5 ">
			<h3>This is documentaion of dashboard</h3>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque praesentium molestiae voluptatum tenetur quas rerum aperiam modi saepe dolor iure eaque minus corporis eum excepturi ab pariatur, quidem autem molestias porro doloribus quibusdam delectus officiis, voluptate? Quasi perferendis sint quis tempora consectetur eveniet aspernatur placeat hic molestiae, nihil. Voluptatem doloribus nobis quos ab vero, id necessitatibus repudiandae neque quam consectetur saepe minima harum, quisquam aliquid excepturi vel. Eius, nobis sapiente veritatis quos, ea non consectetur sed dolorem dolorum eum, mollitia. Illum explicabo sed reprehenderit, corrupti iusto sint quos praesentium est, perferendis aut quidem tenetur veritatis fuga reiciendis earum consequuntur obcaecati quas deserunt dolor, accusamus atque? Ut facere asperiores consequatur architecto, soluta officia consequuntur error numquam itaque commodi amet vitae, laboriosam modi ratione fugit accusantium consectetur quasi. Nisi quibusdam similique ipsa nam consectetur, expedita quis non. Tempora quasi nostrum velit, ex, animi fuga quos, assumenda fugit, amet maxime quaerat architecto sint quis quia doloremque ipsa unde! Quasi magnam vitae dolorum esse alias error, quidem blanditiis, vel debitis nulla sint minima temporibus mollitia id qui maiores asperiores placeat iusto sed. Consequatur minus molestias ducimus, repellendus neque. Dolore, eveniet eius omnis, alias architecto minus! Perspiciatis dicta minima ducimus minus praesentium quisquam, nobis est esse quasi sint quo laudantium ipsum rerum labore, maiores odio, repellendus nostrum assumenda illum quaerat distinctio eius animi pariatur! Perspiciatis, fugiat modi asperiores odio enim fugit voluptates, dolores esse dolorem, at similique? Beatae fugiat totam voluptatem incidunt, maxime, a laboriosam ipsam aperiam nobis repellendus iste, expedita aut, quisquam eligendi. Repellendus voluptas possimus non corrupti officiis deleniti nostrum enim molestias rem odio, quia fuga id blanditiis optio earum odit maiores, reprehenderit nisi et. Enim, fugit odio aliquid sed laboriosam dignissimos, veniam accusamus unde sequi minima dolorem ducimus libero. Magni explicabo eveniet deserunt libero, facere neque mollitia quod tenetur nam doloribus reiciendis.</p>
		</div>

		<div id="dashboard" class="text-justify pt-5 ">
			<h3>This is documentaion of dashboard</h3>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque praesentium molestiae voluptatum tenetur quas rerum aperiam modi saepe dolor iure eaque minus corporis eum excepturi ab pariatur, quidem autem molestias porro doloribus quibusdam delectus officiis, voluptate? Quasi perferendis sint quis tempora consectetur eveniet aspernatur placeat hic molestiae, nihil. Voluptatem doloribus nobis quos ab vero, id necessitatibus repudiandae neque quam consectetur saepe minima harum, quisquam aliquid excepturi vel. Eius, nobis sapiente veritatis quos, ea non consectetur sed dolorem dolorum eum, mollitia. Illum explicabo sed reprehenderit, corrupti iusto sint quos praesentium est, perferendis aut quidem tenetur veritatis fuga reiciendis earum consequuntur obcaecati quas deserunt dolor, accusamus atque? Ut facere asperiores consequatur architecto, soluta officia consequuntur error numquam itaque commodi amet vitae, laboriosam modi ratione fugit accusantium consectetur quasi. Nisi quibusdam similique ipsa nam consectetur, expedita quis non. Tempora quasi nostrum velit, ex, animi fuga quos, assumenda fugit, amet maxime quaerat architecto sint quis quia doloremque ipsa unde! Quasi magnam vitae dolorum esse alias error, quidem blanditiis, vel debitis nulla sint minima temporibus mollitia id qui maiores asperiores placeat iusto sed. Consequatur minus molestias ducimus, repellendus neque. Dolore, eveniet eius omnis, alias architecto minus! Perspiciatis dicta minima ducimus minus praesentium quisquam, nobis est esse quasi sint quo laudantium ipsum rerum labore, maiores odio, repellendus nostrum assumenda illum quaerat distinctio eius animi pariatur! Perspiciatis, fugiat modi asperiores odio enim fugit voluptates, dolores esse dolorem, at similique? Beatae fugiat totam voluptatem incidunt, maxime, a laboriosam ipsam aperiam nobis repellendus iste, expedita aut, quisquam eligendi. Repellendus voluptas possimus non corrupti officiis deleniti nostrum enim molestias rem odio, quia fuga id blanditiis optio earum odit maiores, reprehenderit nisi et. Enim, fugit odio aliquid sed laboriosam dignissimos, veniam accusamus unde sequi minima dolorem ducimus libero. Magni explicabo eveniet deserunt libero, facere neque mollitia quod tenetur nam doloribus reiciendis.</p>
		</div>

		<div id="dashboard" class="text-justify pt-5 ">
			<h3>This is documentaion of dashboard</h3>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque praesentium molestiae voluptatum tenetur quas rerum aperiam modi saepe dolor iure eaque minus corporis eum excepturi ab pariatur, quidem autem molestias porro doloribus quibusdam delectus officiis, voluptate? Quasi perferendis sint quis tempora consectetur eveniet aspernatur placeat hic molestiae, nihil. Voluptatem doloribus nobis quos ab vero, id necessitatibus repudiandae neque quam consectetur saepe minima harum, quisquam aliquid excepturi vel. Eius, nobis sapiente veritatis quos, ea non consectetur sed dolorem dolorum eum, mollitia. Illum explicabo sed reprehenderit, corrupti iusto sint quos praesentium est, perferendis aut quidem tenetur veritatis fuga reiciendis earum consequuntur obcaecati quas deserunt dolor, accusamus atque? Ut facere asperiores consequatur architecto, soluta officia consequuntur error numquam itaque commodi amet vitae, laboriosam modi ratione fugit accusantium consectetur quasi. Nisi quibusdam similique ipsa nam consectetur, expedita quis non. Tempora quasi nostrum velit, ex, animi fuga quos, assumenda fugit, amet maxime quaerat architecto sint quis quia doloremque ipsa unde! Quasi magnam vitae dolorum esse alias error, quidem blanditiis, vel debitis nulla sint minima temporibus mollitia id qui maiores asperiores placeat iusto sed. Consequatur minus molestias ducimus, repellendus neque. Dolore, eveniet eius omnis, alias architecto minus! Perspiciatis dicta minima ducimus minus praesentium quisquam, nobis est esse quasi sint quo laudantium ipsum rerum labore, maiores odio, repellendus nostrum assumenda illum quaerat distinctio eius animi pariatur! Perspiciatis, fugiat modi asperiores odio enim fugit voluptates, dolores esse dolorem, at similique? Beatae fugiat totam voluptatem incidunt, maxime, a laboriosam ipsam aperiam nobis repellendus iste, expedita aut, quisquam eligendi. Repellendus voluptas possimus non corrupti officiis deleniti nostrum enim molestias rem odio, quia fuga id blanditiis optio earum odit maiores, reprehenderit nisi et. Enim, fugit odio aliquid sed laboriosam dignissimos, veniam accusamus unde sequi minima dolorem ducimus libero. Magni explicabo eveniet deserunt libero, facere neque mollitia quod tenetur nam doloribus reiciendis.</p>
		</div>

		<div id="dashboard" class="text-justify pt-5 ">
			<h3>This is documentaion of dashboard</h3>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque praesentium molestiae voluptatum tenetur quas rerum aperiam modi saepe dolor iure eaque minus corporis eum excepturi ab pariatur, quidem autem molestias porro doloribus quibusdam delectus officiis, voluptate? Quasi perferendis sint quis tempora consectetur eveniet aspernatur placeat hic molestiae, nihil. Voluptatem doloribus nobis quos ab vero, id necessitatibus repudiandae neque quam consectetur saepe minima harum, quisquam aliquid excepturi vel. Eius, nobis sapiente veritatis quos, ea non consectetur sed dolorem dolorum eum, mollitia. Illum explicabo sed reprehenderit, corrupti iusto sint quos praesentium est, perferendis aut quidem tenetur veritatis fuga reiciendis earum consequuntur obcaecati quas deserunt dolor, accusamus atque? Ut facere asperiores consequatur architecto, soluta officia consequuntur error numquam itaque commodi amet vitae, laboriosam modi ratione fugit accusantium consectetur quasi. Nisi quibusdam similique ipsa nam consectetur, expedita quis non. Tempora quasi nostrum velit, ex, animi fuga quos, assumenda fugit, amet maxime quaerat architecto sint quis quia doloremque ipsa unde! Quasi magnam vitae dolorum esse alias error, quidem blanditiis, vel debitis nulla sint minima temporibus mollitia id qui maiores asperiores placeat iusto sed. Consequatur minus molestias ducimus, repellendus neque. Dolore, eveniet eius omnis, alias architecto minus! Perspiciatis dicta minima ducimus minus praesentium quisquam, nobis est esse quasi sint quo laudantium ipsum rerum labore, maiores odio, repellendus nostrum assumenda illum quaerat distinctio eius animi pariatur! Perspiciatis, fugiat modi asperiores odio enim fugit voluptates, dolores esse dolorem, at similique? Beatae fugiat totam voluptatem incidunt, maxime, a laboriosam ipsam aperiam nobis repellendus iste, expedita aut, quisquam eligendi. Repellendus voluptas possimus non corrupti officiis deleniti nostrum enim molestias rem odio, quia fuga id blanditiis optio earum odit maiores, reprehenderit nisi et. Enim, fugit odio aliquid sed laboriosam dignissimos, veniam accusamus unde sequi minima dolorem ducimus libero. Magni explicabo eveniet deserunt libero, facere neque mollitia quod tenetur nam doloribus reiciendis.</p>
		</div>

		<div id="dashboard" class="text-justify pt-5 ">
			<h3>This is documentaion of dashboard</h3>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque praesentium molestiae voluptatum tenetur quas rerum aperiam modi saepe dolor iure eaque minus corporis eum excepturi ab pariatur, quidem autem molestias porro doloribus quibusdam delectus officiis, voluptate? Quasi perferendis sint quis tempora consectetur eveniet aspernatur placeat hic molestiae, nihil. Voluptatem doloribus nobis quos ab vero, id necessitatibus repudiandae neque quam consectetur saepe minima harum, quisquam aliquid excepturi vel. Eius, nobis sapiente veritatis quos, ea non consectetur sed dolorem dolorum eum, mollitia. Illum explicabo sed reprehenderit, corrupti iusto sint quos praesentium est, perferendis aut quidem tenetur veritatis fuga reiciendis earum consequuntur obcaecati quas deserunt dolor, accusamus atque? Ut facere asperiores consequatur architecto, soluta officia consequuntur error numquam itaque commodi amet vitae, laboriosam modi ratione fugit accusantium consectetur quasi. Nisi quibusdam similique ipsa nam consectetur, expedita quis non. Tempora quasi nostrum velit, ex, animi fuga quos, assumenda fugit, amet maxime quaerat architecto sint quis quia doloremque ipsa unde! Quasi magnam vitae dolorum esse alias error, quidem blanditiis, vel debitis nulla sint minima temporibus mollitia id qui maiores asperiores placeat iusto sed. Consequatur minus molestias ducimus, repellendus neque. Dolore, eveniet eius omnis, alias architecto minus! Perspiciatis dicta minima ducimus minus praesentium quisquam, nobis est esse quasi sint quo laudantium ipsum rerum labore, maiores odio, repellendus nostrum assumenda illum quaerat distinctio eius animi pariatur! Perspiciatis, fugiat modi asperiores odio enim fugit voluptates, dolores esse dolorem, at similique? Beatae fugiat totam voluptatem incidunt, maxime, a laboriosam ipsam aperiam nobis repellendus iste, expedita aut, quisquam eligendi. Repellendus voluptas possimus non corrupti officiis deleniti nostrum enim molestias rem odio, quia fuga id blanditiis optio earum odit maiores, reprehenderit nisi et. Enim, fugit odio aliquid sed laboriosam dignissimos, veniam accusamus unde sequi minima dolorem ducimus libero. Magni explicabo eveniet deserunt libero, facere neque mollitia quod tenetur nam doloribus reiciendis.</p>
		</div>

		<div id="dashboard" class="text-justify pt-5 ">
			<h3>This is documentaion of dashboard</h3>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque praesentium molestiae voluptatum tenetur quas rerum aperiam modi saepe dolor iure eaque minus corporis eum excepturi ab pariatur, quidem autem molestias porro doloribus quibusdam delectus officiis, voluptate? Quasi perferendis sint quis tempora consectetur eveniet aspernatur placeat hic molestiae, nihil. Voluptatem doloribus nobis quos ab vero, id necessitatibus repudiandae neque quam consectetur saepe minima harum, quisquam aliquid excepturi vel. Eius, nobis sapiente veritatis quos, ea non consectetur sed dolorem dolorum eum, mollitia. Illum explicabo sed reprehenderit, corrupti iusto sint quos praesentium est, perferendis aut quidem tenetur veritatis fuga reiciendis earum consequuntur obcaecati quas deserunt dolor, accusamus atque? Ut facere asperiores consequatur architecto, soluta officia consequuntur error numquam itaque commodi amet vitae, laboriosam modi ratione fugit accusantium consectetur quasi. Nisi quibusdam similique ipsa nam consectetur, expedita quis non. Tempora quasi nostrum velit, ex, animi fuga quos, assumenda fugit, amet maxime quaerat architecto sint quis quia doloremque ipsa unde! Quasi magnam vitae dolorum esse alias error, quidem blanditiis, vel debitis nulla sint minima temporibus mollitia id qui maiores asperiores placeat iusto sed. Consequatur minus molestias ducimus, repellendus neque. Dolore, eveniet eius omnis, alias architecto minus! Perspiciatis dicta minima ducimus minus praesentium quisquam, nobis est esse quasi sint quo laudantium ipsum rerum labore, maiores odio, repellendus nostrum assumenda illum quaerat distinctio eius animi pariatur! Perspiciatis, fugiat modi asperiores odio enim fugit voluptates, dolores esse dolorem, at similique? Beatae fugiat totam voluptatem incidunt, maxime, a laboriosam ipsam aperiam nobis repellendus iste, expedita aut, quisquam eligendi. Repellendus voluptas possimus non corrupti officiis deleniti nostrum enim molestias rem odio, quia fuga id blanditiis optio earum odit maiores, reprehenderit nisi et. Enim, fugit odio aliquid sed laboriosam dignissimos, veniam accusamus unde sequi minima dolorem ducimus libero. Magni explicabo eveniet deserunt libero, facere neque mollitia quod tenetur nam doloribus reiciendis.</p>
		</div>

		<div id="dashboard" class="text-justify pt-5 ">
			<h3>This is documentaion of dashboard</h3>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque praesentium molestiae voluptatum tenetur quas rerum aperiam modi saepe dolor iure eaque minus corporis eum excepturi ab pariatur, quidem autem molestias porro doloribus quibusdam delectus officiis, voluptate? Quasi perferendis sint quis tempora consectetur eveniet aspernatur placeat hic molestiae, nihil. Voluptatem doloribus nobis quos ab vero, id necessitatibus repudiandae neque quam consectetur saepe minima harum, quisquam aliquid excepturi vel. Eius, nobis sapiente veritatis quos, ea non consectetur sed dolorem dolorum eum, mollitia. Illum explicabo sed reprehenderit, corrupti iusto sint quos praesentium est, perferendis aut quidem tenetur veritatis fuga reiciendis earum consequuntur obcaecati quas deserunt dolor, accusamus atque? Ut facere asperiores consequatur architecto, soluta officia consequuntur error numquam itaque commodi amet vitae, laboriosam modi ratione fugit accusantium consectetur quasi. Nisi quibusdam similique ipsa nam consectetur, expedita quis non. Tempora quasi nostrum velit, ex, animi fuga quos, assumenda fugit, amet maxime quaerat architecto sint quis quia doloremque ipsa unde! Quasi magnam vitae dolorum esse alias error, quidem blanditiis, vel debitis nulla sint minima temporibus mollitia id qui maiores asperiores placeat iusto sed. Consequatur minus molestias ducimus, repellendus neque. Dolore, eveniet eius omnis, alias architecto minus! Perspiciatis dicta minima ducimus minus praesentium quisquam, nobis est esse quasi sint quo laudantium ipsum rerum labore, maiores odio, repellendus nostrum assumenda illum quaerat distinctio eius animi pariatur! Perspiciatis, fugiat modi asperiores odio enim fugit voluptates, dolores esse dolorem, at similique? Beatae fugiat totam voluptatem incidunt, maxime, a laboriosam ipsam aperiam nobis repellendus iste, expedita aut, quisquam eligendi. Repellendus voluptas possimus non corrupti officiis deleniti nostrum enim molestias rem odio, quia fuga id blanditiis optio earum odit maiores, reprehenderit nisi et. Enim, fugit odio aliquid sed laboriosam dignissimos, veniam accusamus unde sequi minima dolorem ducimus libero. Magni explicabo eveniet deserunt libero, facere neque mollitia quod tenetur nam doloribus reiciendis.</p>
		</div>

	</div>

	<div class="back-end" >

		<div id="dashboard" class="text-justify pt-5 ">
			<h3>This is documentaion of dashboard</h3>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque praesentium molestiae voluptatum tenetur quas rerum aperiam modi saepe dolor iure eaque minus corporis eum excepturi ab pariatur, quidem autem molestias porro doloribus quibusdam delectus officiis, voluptate? Quasi perferendis sint quis tempora consectetur eveniet aspernatur placeat hic molestiae, nihil. Voluptatem doloribus nobis quos ab vero, id necessitatibus repudiandae neque quam consectetur saepe minima harum, quisquam aliquid excepturi vel. Eius, nobis sapiente veritatis quos, ea non consectetur sed dolorem dolorum eum, mollitia. Illum explicabo sed reprehenderit, corrupti iusto sint quos praesentium est, perferendis aut quidem tenetur veritatis fuga reiciendis earum consequuntur obcaecati quas deserunt dolor, accusamus atque? Ut facere asperiores consequatur architecto, soluta officia consequuntur error numquam itaque commodi amet vitae, laboriosam modi ratione fugit accusantium consectetur quasi. Nisi quibusdam similique ipsa nam consectetur, expedita quis non. Tempora quasi nostrum velit, ex, animi fuga quos, assumenda fugit, amet maxime quaerat architecto sint quis quia doloremque ipsa unde! Quasi magnam vitae dolorum esse alias error, quidem blanditiis, vel debitis nulla sint minima temporibus mollitia id qui maiores asperiores placeat iusto sed. Consequatur minus molestias ducimus, repellendus neque. Dolore, eveniet eius omnis, alias architecto minus! Perspiciatis dicta minima ducimus minus praesentium quisquam, nobis est esse quasi sint quo laudantium ipsum rerum labore, maiores odio, repellendus nostrum assumenda illum quaerat distinctio eius animi pariatur! Perspiciatis, fugiat modi asperiores odio enim fugit voluptates, dolores esse dolorem, at similique? Beatae fugiat totam voluptatem incidunt, maxime, a laboriosam ipsam aperiam nobis repellendus iste, expedita aut, quisquam eligendi. Repellendus voluptas possimus non corrupti officiis deleniti nostrum enim molestias rem odio, quia fuga id blanditiis optio earum odit maiores, reprehenderit nisi et. Enim, fugit odio aliquid sed laboriosam dignissimos, veniam accusamus unde sequi minima dolorem ducimus libero. Magni explicabo eveniet deserunt libero, facere neque mollitia quod tenetur nam doloribus reiciendis.</p>
		</div>

		<div id="dashboard" class="text-justify pt-5 ">
			<h3>This is documentaion of dashboard</h3>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque praesentium molestiae voluptatum tenetur quas rerum aperiam modi saepe dolor iure eaque minus corporis eum excepturi ab pariatur, quidem autem molestias porro doloribus quibusdam delectus officiis, voluptate? Quasi perferendis sint quis tempora consectetur eveniet aspernatur placeat hic molestiae, nihil. Voluptatem doloribus nobis quos ab vero, id necessitatibus repudiandae neque quam consectetur saepe minima harum, quisquam aliquid excepturi vel. Eius, nobis sapiente veritatis quos, ea non consectetur sed dolorem dolorum eum, mollitia. Illum explicabo sed reprehenderit, corrupti iusto sint quos praesentium est, perferendis aut quidem tenetur veritatis fuga reiciendis earum consequuntur obcaecati quas deserunt dolor, accusamus atque? Ut facere asperiores consequatur architecto, soluta officia consequuntur error numquam itaque commodi amet vitae, laboriosam modi ratione fugit accusantium consectetur quasi. Nisi quibusdam similique ipsa nam consectetur, expedita quis non. Tempora quasi nostrum velit, ex, animi fuga quos, assumenda fugit, amet maxime quaerat architecto sint quis quia doloremque ipsa unde! Quasi magnam vitae dolorum esse alias error, quidem blanditiis, vel debitis nulla sint minima temporibus mollitia id qui maiores asperiores placeat iusto sed. Consequatur minus molestias ducimus, repellendus neque. Dolore, eveniet eius omnis, alias architecto minus! Perspiciatis dicta minima ducimus minus praesentium quisquam, nobis est esse quasi sint quo laudantium ipsum rerum labore, maiores odio, repellendus nostrum assumenda illum quaerat distinctio eius animi pariatur! Perspiciatis, fugiat modi asperiores odio enim fugit voluptates, dolores esse dolorem, at similique? Beatae fugiat totam voluptatem incidunt, maxime, a laboriosam ipsam aperiam nobis repellendus iste, expedita aut, quisquam eligendi. Repellendus voluptas possimus non corrupti officiis deleniti nostrum enim molestias rem odio, quia fuga id blanditiis optio earum odit maiores, reprehenderit nisi et. Enim, fugit odio aliquid sed laboriosam dignissimos, veniam accusamus unde sequi minima dolorem ducimus libero. Magni explicabo eveniet deserunt libero, facere neque mollitia quod tenetur nam doloribus reiciendis.</p>
		</div>

		<div id="dashboard" class="text-justify pt-5 ">
			<h3>This is documentaion of dashboard</h3>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque praesentium molestiae voluptatum tenetur quas rerum aperiam modi saepe dolor iure eaque minus corporis eum excepturi ab pariatur, quidem autem molestias porro doloribus quibusdam delectus officiis, voluptate? Quasi perferendis sint quis tempora consectetur eveniet aspernatur placeat hic molestiae, nihil. Voluptatem doloribus nobis quos ab vero, id necessitatibus repudiandae neque quam consectetur saepe minima harum, quisquam aliquid excepturi vel. Eius, nobis sapiente veritatis quos, ea non consectetur sed dolorem dolorum eum, mollitia. Illum explicabo sed reprehenderit, corrupti iusto sint quos praesentium est, perferendis aut quidem tenetur veritatis fuga reiciendis earum consequuntur obcaecati quas deserunt dolor, accusamus atque? Ut facere asperiores consequatur architecto, soluta officia consequuntur error numquam itaque commodi amet vitae, laboriosam modi ratione fugit accusantium consectetur quasi. Nisi quibusdam similique ipsa nam consectetur, expedita quis non. Tempora quasi nostrum velit, ex, animi fuga quos, assumenda fugit, amet maxime quaerat architecto sint quis quia doloremque ipsa unde! Quasi magnam vitae dolorum esse alias error, quidem blanditiis, vel debitis nulla sint minima temporibus mollitia id qui maiores asperiores placeat iusto sed. Consequatur minus molestias ducimus, repellendus neque. Dolore, eveniet eius omnis, alias architecto minus! Perspiciatis dicta minima ducimus minus praesentium quisquam, nobis est esse quasi sint quo laudantium ipsum rerum labore, maiores odio, repellendus nostrum assumenda illum quaerat distinctio eius animi pariatur! Perspiciatis, fugiat modi asperiores odio enim fugit voluptates, dolores esse dolorem, at similique? Beatae fugiat totam voluptatem incidunt, maxime, a laboriosam ipsam aperiam nobis repellendus iste, expedita aut, quisquam eligendi. Repellendus voluptas possimus non corrupti officiis deleniti nostrum enim molestias rem odio, quia fuga id blanditiis optio earum odit maiores, reprehenderit nisi et. Enim, fugit odio aliquid sed laboriosam dignissimos, veniam accusamus unde sequi minima dolorem ducimus libero. Magni explicabo eveniet deserunt libero, facere neque mollitia quod tenetur nam doloribus reiciendis.</p>
		</div>

		<div id="dashboard" class="text-justify pt-5 ">
			<h3>This is documentaion of dashboard</h3>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque praesentium molestiae voluptatum tenetur quas rerum aperiam modi saepe dolor iure eaque minus corporis eum excepturi ab pariatur, quidem autem molestias porro doloribus quibusdam delectus officiis, voluptate? Quasi perferendis sint quis tempora consectetur eveniet aspernatur placeat hic molestiae, nihil. Voluptatem doloribus nobis quos ab vero, id necessitatibus repudiandae neque quam consectetur saepe minima harum, quisquam aliquid excepturi vel. Eius, nobis sapiente veritatis quos, ea non consectetur sed dolorem dolorum eum, mollitia. Illum explicabo sed reprehenderit, corrupti iusto sint quos praesentium est, perferendis aut quidem tenetur veritatis fuga reiciendis earum consequuntur obcaecati quas deserunt dolor, accusamus atque? Ut facere asperiores consequatur architecto, soluta officia consequuntur error numquam itaque commodi amet vitae, laboriosam modi ratione fugit accusantium consectetur quasi. Nisi quibusdam similique ipsa nam consectetur, expedita quis non. Tempora quasi nostrum velit, ex, animi fuga quos, assumenda fugit, amet maxime quaerat architecto sint quis quia doloremque ipsa unde! Quasi magnam vitae dolorum esse alias error, quidem blanditiis, vel debitis nulla sint minima temporibus mollitia id qui maiores asperiores placeat iusto sed. Consequatur minus molestias ducimus, repellendus neque. Dolore, eveniet eius omnis, alias architecto minus! Perspiciatis dicta minima ducimus minus praesentium quisquam, nobis est esse quasi sint quo laudantium ipsum rerum labore, maiores odio, repellendus nostrum assumenda illum quaerat distinctio eius animi pariatur! Perspiciatis, fugiat modi asperiores odio enim fugit voluptates, dolores esse dolorem, at similique? Beatae fugiat totam voluptatem incidunt, maxime, a laboriosam ipsam aperiam nobis repellendus iste, expedita aut, quisquam eligendi. Repellendus voluptas possimus non corrupti officiis deleniti nostrum enim molestias rem odio, quia fuga id blanditiis optio earum odit maiores, reprehenderit nisi et. Enim, fugit odio aliquid sed laboriosam dignissimos, veniam accusamus unde sequi minima dolorem ducimus libero. Magni explicabo eveniet deserunt libero, facere neque mollitia quod tenetur nam doloribus reiciendis.</p>
		</div>

		<div id="dashboard" class="text-justify pt-5 ">
			<h3>This is documentaion of dashboard</h3>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque praesentium molestiae voluptatum tenetur quas rerum aperiam modi saepe dolor iure eaque minus corporis eum excepturi ab pariatur, quidem autem molestias porro doloribus quibusdam delectus officiis, voluptate? Quasi perferendis sint quis tempora consectetur eveniet aspernatur placeat hic molestiae, nihil. Voluptatem doloribus nobis quos ab vero, id necessitatibus repudiandae neque quam consectetur saepe minima harum, quisquam aliquid excepturi vel. Eius, nobis sapiente veritatis quos, ea non consectetur sed dolorem dolorum eum, mollitia. Illum explicabo sed reprehenderit, corrupti iusto sint quos praesentium est, perferendis aut quidem tenetur veritatis fuga reiciendis earum consequuntur obcaecati quas deserunt dolor, accusamus atque? Ut facere asperiores consequatur architecto, soluta officia consequuntur error numquam itaque commodi amet vitae, laboriosam modi ratione fugit accusantium consectetur quasi. Nisi quibusdam similique ipsa nam consectetur, expedita quis non. Tempora quasi nostrum velit, ex, animi fuga quos, assumenda fugit, amet maxime quaerat architecto sint quis quia doloremque ipsa unde! Quasi magnam vitae dolorum esse alias error, quidem blanditiis, vel debitis nulla sint minima temporibus mollitia id qui maiores asperiores placeat iusto sed. Consequatur minus molestias ducimus, repellendus neque. Dolore, eveniet eius omnis, alias architecto minus! Perspiciatis dicta minima ducimus minus praesentium quisquam, nobis est esse quasi sint quo laudantium ipsum rerum labore, maiores odio, repellendus nostrum assumenda illum quaerat distinctio eius animi pariatur! Perspiciatis, fugiat modi asperiores odio enim fugit voluptates, dolores esse dolorem, at similique? Beatae fugiat totam voluptatem incidunt, maxime, a laboriosam ipsam aperiam nobis repellendus iste, expedita aut, quisquam eligendi. Repellendus voluptas possimus non corrupti officiis deleniti nostrum enim molestias rem odio, quia fuga id blanditiis optio earum odit maiores, reprehenderit nisi et. Enim, fugit odio aliquid sed laboriosam dignissimos, veniam accusamus unde sequi minima dolorem ducimus libero. Magni explicabo eveniet deserunt libero, facere neque mollitia quod tenetur nam doloribus reiciendis.</p>
		</div>

		<div id="dashboard" class="text-justify pt-5 ">
			<h3>This is documentaion of dashboard</h3>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque praesentium molestiae voluptatum tenetur quas rerum aperiam modi saepe dolor iure eaque minus corporis eum excepturi ab pariatur, quidem autem molestias porro doloribus quibusdam delectus officiis, voluptate? Quasi perferendis sint quis tempora consectetur eveniet aspernatur placeat hic molestiae, nihil. Voluptatem doloribus nobis quos ab vero, id necessitatibus repudiandae neque quam consectetur saepe minima harum, quisquam aliquid excepturi vel. Eius, nobis sapiente veritatis quos, ea non consectetur sed dolorem dolorum eum, mollitia. Illum explicabo sed reprehenderit, corrupti iusto sint quos praesentium est, perferendis aut quidem tenetur veritatis fuga reiciendis earum consequuntur obcaecati quas deserunt dolor, accusamus atque? Ut facere asperiores consequatur architecto, soluta officia consequuntur error numquam itaque commodi amet vitae, laboriosam modi ratione fugit accusantium consectetur quasi. Nisi quibusdam similique ipsa nam consectetur, expedita quis non. Tempora quasi nostrum velit, ex, animi fuga quos, assumenda fugit, amet maxime quaerat architecto sint quis quia doloremque ipsa unde! Quasi magnam vitae dolorum esse alias error, quidem blanditiis, vel debitis nulla sint minima temporibus mollitia id qui maiores asperiores placeat iusto sed. Consequatur minus molestias ducimus, repellendus neque. Dolore, eveniet eius omnis, alias architecto minus! Perspiciatis dicta minima ducimus minus praesentium quisquam, nobis est esse quasi sint quo laudantium ipsum rerum labore, maiores odio, repellendus nostrum assumenda illum quaerat distinctio eius animi pariatur! Perspiciatis, fugiat modi asperiores odio enim fugit voluptates, dolores esse dolorem, at similique? Beatae fugiat totam voluptatem incidunt, maxime, a laboriosam ipsam aperiam nobis repellendus iste, expedita aut, quisquam eligendi. Repellendus voluptas possimus non corrupti officiis deleniti nostrum enim molestias rem odio, quia fuga id blanditiis optio earum odit maiores, reprehenderit nisi et. Enim, fugit odio aliquid sed laboriosam dignissimos, veniam accusamus unde sequi minima dolorem ducimus libero. Magni explicabo eveniet deserunt libero, facere neque mollitia quod tenetur nam doloribus reiciendis.</p>
		</div>

		<div id="b-offer-doc" class="text-justify pt-5 ">
			<h3>This is documentaion of b-offer-doc</h3>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque praesentium molestiae voluptatum tenetur quas rerum aperiam modi saepe dolor iure eaque minus corporis eum excepturi ab pariatur, quidem autem molestias porro doloribus quibusdam delectus officiis, voluptate? Quasi perferendis sint quis tempora consectetur eveniet aspernatur placeat hic molestiae, nihil. Voluptatem doloribus nobis quos ab vero, id necessitatibus repudiandae neque quam consectetur saepe minima harum, quisquam aliquid excepturi vel. Eius, nobis sapiente veritatis quos, ea non consectetur sed dolorem dolorum eum, mollitia. Illum explicabo sed reprehenderit, corrupti iusto sint quos praesentium est, perferendis aut quidem tenetur veritatis fuga reiciendis earum consequuntur obcaecati quas deserunt dolor, accusamus atque? Ut facere asperiores consequatur architecto, soluta officia consequuntur error numquam itaque commodi amet vitae, laboriosam modi ratione fugit accusantium consectetur quasi. Nisi quibusdam similique ipsa nam consectetur, expedita quis non. Tempora quasi nostrum velit, ex, animi fuga quos, assumenda fugit, amet maxime quaerat architecto sint quis quia doloremque ipsa unde! Quasi magnam vitae dolorum esse alias error, quidem blanditiis, vel debitis nulla sint minima temporibus mollitia id qui maiores asperiores placeat iusto sed. Consequatur minus molestias ducimus, repellendus neque. Dolore, eveniet eius omnis, alias architecto minus! Perspiciatis dicta minima ducimus minus praesentium quisquam, nobis est esse quasi sint quo laudantium ipsum rerum labore, maiores odio, repellendus nostrum assumenda illum quaerat distinctio eius animi pariatur! Perspiciatis, fugiat modi asperiores odio enim fugit voluptates, dolores esse dolorem, at similique? Beatae fugiat totam voluptatem incidunt, maxime, a laboriosam ipsam aperiam nobis repellendus iste, expedita aut, quisquam eligendi. Repellendus voluptas possimus non corrupti officiis deleniti nostrum enim molestias rem odio, quia fuga id blanditiis optio earum odit maiores, reprehenderit nisi et. Enim, fugit odio aliquid sed laboriosam dignissimos, veniam accusamus unde sequi minima dolorem ducimus libero. Magni explicabo eveniet deserunt libero, facere neque mollitia quod tenetur nam doloribus reiciendis.</p>
		</div>

		<div id="dashboard" class="text-justify pt-5 ">
			<h3>This is documentaion of dashboard</h3>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque praesentium molestiae voluptatum tenetur quas rerum aperiam modi saepe dolor iure eaque minus corporis eum excepturi ab pariatur, quidem autem molestias porro doloribus quibusdam delectus officiis, voluptate? Quasi perferendis sint quis tempora consectetur eveniet aspernatur placeat hic molestiae, nihil. Voluptatem doloribus nobis quos ab vero, id necessitatibus repudiandae neque quam consectetur saepe minima harum, quisquam aliquid excepturi vel. Eius, nobis sapiente veritatis quos, ea non consectetur sed dolorem dolorum eum, mollitia. Illum explicabo sed reprehenderit, corrupti iusto sint quos praesentium est, perferendis aut quidem tenetur veritatis fuga reiciendis earum consequuntur obcaecati quas deserunt dolor, accusamus atque? Ut facere asperiores consequatur architecto, soluta officia consequuntur error numquam itaque commodi amet vitae, laboriosam modi ratione fugit accusantium consectetur quasi. Nisi quibusdam similique ipsa nam consectetur, expedita quis non. Tempora quasi nostrum velit, ex, animi fuga quos, assumenda fugit, amet maxime quaerat architecto sint quis quia doloremque ipsa unde! Quasi magnam vitae dolorum esse alias error, quidem blanditiis, vel debitis nulla sint minima temporibus mollitia id qui maiores asperiores placeat iusto sed. Consequatur minus molestias ducimus, repellendus neque. Dolore, eveniet eius omnis, alias architecto minus! Perspiciatis dicta minima ducimus minus praesentium quisquam, nobis est esse quasi sint quo laudantium ipsum rerum labore, maiores odio, repellendus nostrum assumenda illum quaerat distinctio eius animi pariatur! Perspiciatis, fugiat modi asperiores odio enim fugit voluptates, dolores esse dolorem, at similique? Beatae fugiat totam voluptatem incidunt, maxime, a laboriosam ipsam aperiam nobis repellendus iste, expedita aut, quisquam eligendi. Repellendus voluptas possimus non corrupti officiis deleniti nostrum enim molestias rem odio, quia fuga id blanditiis optio earum odit maiores, reprehenderit nisi et. Enim, fugit odio aliquid sed laboriosam dignissimos, veniam accusamus unde sequi minima dolorem ducimus libero. Magni explicabo eveniet deserunt libero, facere neque mollitia quod tenetur nam doloribus reiciendis.</p>
		</div>

		<div id="" class="text-justify pt-5 ">
			<h3>This is documentaion of dashboard</h3>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque praesentium molestiae voluptatum tenetur quas rerum aperiam modi saepe dolor iure eaque minus corporis eum excepturi ab pariatur, quidem autem molestias porro doloribus quibusdam delectus officiis, voluptate? Quasi perferendis sint quis tempora consectetur eveniet aspernatur placeat hic molestiae, nihil. Voluptatem doloribus nobis quos ab vero, id necessitatibus repudiandae neque quam consectetur saepe minima harum, quisquam aliquid excepturi vel. Eius, nobis sapiente veritatis quos, ea non consectetur sed dolorem dolorum eum, mollitia. Illum explicabo sed reprehenderit, corrupti iusto sint quos praesentium est, perferendis aut quidem tenetur veritatis fuga reiciendis earum consequuntur obcaecati quas deserunt dolor, accusamus atque? Ut facere asperiores consequatur architecto, soluta officia consequuntur error numquam itaque commodi amet vitae, laboriosam modi ratione fugit accusantium consectetur quasi. Nisi quibusdam similique ipsa nam consectetur, expedita quis non. Tempora quasi nostrum velit, ex, animi fuga quos, assumenda fugit, amet maxime quaerat architecto sint quis quia doloremque ipsa unde! Quasi magnam vitae dolorum esse alias error, quidem blanditiis, vel debitis nulla sint minima temporibus mollitia id qui maiores asperiores placeat iusto sed. Consequatur minus molestias ducimus, repellendus neque. Dolore, eveniet eius omnis, alias architecto minus! Perspiciatis dicta minima ducimus minus praesentium quisquam, nobis est esse quasi sint quo laudantium ipsum rerum labore, maiores odio, repellendus nostrum assumenda illum quaerat distinctio eius animi pariatur! Perspiciatis, fugiat modi asperiores odio enim fugit voluptates, dolores esse dolorem, at similique? Beatae fugiat totam voluptatem incidunt, maxime, a laboriosam ipsam aperiam nobis repellendus iste, expedita aut, quisquam eligendi. Repellendus voluptas possimus non corrupti officiis deleniti nostrum enim molestias rem odio, quia fuga id blanditiis optio earum odit maiores, reprehenderit nisi et. Enim, fugit odio aliquid sed laboriosam dignissimos, veniam accusamus unde sequi minima dolorem ducimus libero. Magni explicabo eveniet deserunt libero, facere neque mollitia quod tenetur nam doloribus reiciendis.</p>
		</div>

		<div id="dashboard" class="text-justify pt-5 ">
			<h3>This is documentaion of dashboard</h3>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque praesentium molestiae voluptatum tenetur quas rerum aperiam modi saepe dolor iure eaque minus corporis eum excepturi ab pariatur, quidem autem molestias porro doloribus quibusdam delectus officiis, voluptate? Quasi perferendis sint quis tempora consectetur eveniet aspernatur placeat hic molestiae, nihil. Voluptatem doloribus nobis quos ab vero, id necessitatibus repudiandae neque quam consectetur saepe minima harum, quisquam aliquid excepturi vel. Eius, nobis sapiente veritatis quos, ea non consectetur sed dolorem dolorum eum, mollitia. Illum explicabo sed reprehenderit, corrupti iusto sint quos praesentium est, perferendis aut quidem tenetur veritatis fuga reiciendis earum consequuntur obcaecati quas deserunt dolor, accusamus atque? Ut facere asperiores consequatur architecto, soluta officia consequuntur error numquam itaque commodi amet vitae, laboriosam modi ratione fugit accusantium consectetur quasi. Nisi quibusdam similique ipsa nam consectetur, expedita quis non. Tempora quasi nostrum velit, ex, animi fuga quos, assumenda fugit, amet maxime quaerat architecto sint quis quia doloremque ipsa unde! Quasi magnam vitae dolorum esse alias error, quidem blanditiis, vel debitis nulla sint minima temporibus mollitia id qui maiores asperiores placeat iusto sed. Consequatur minus molestias ducimus, repellendus neque. Dolore, eveniet eius omnis, alias architecto minus! Perspiciatis dicta minima ducimus minus praesentium quisquam, nobis est esse quasi sint quo laudantium ipsum rerum labore, maiores odio, repellendus nostrum assumenda illum quaerat distinctio eius animi pariatur! Perspiciatis, fugiat modi asperiores odio enim fugit voluptates, dolores esse dolorem, at similique? Beatae fugiat totam voluptatem incidunt, maxime, a laboriosam ipsam aperiam nobis repellendus iste, expedita aut, quisquam eligendi. Repellendus voluptas possimus non corrupti officiis deleniti nostrum enim molestias rem odio, quia fuga id blanditiis optio earum odit maiores, reprehenderit nisi et. Enim, fugit odio aliquid sed laboriosam dignissimos, veniam accusamus unde sequi minima dolorem ducimus libero. Magni explicabo eveniet deserunt libero, facere neque mollitia quod tenetur nam doloribus reiciendis.</p>
		</div>

	</div>

</div>




@endsection
@section('footer-section')
<script>


</script>
@endsection
